print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
tip = float(input("What percentage tip would you like to give? 10 12 15 "))
people = float(input("How many people to split the bill? "))
b = (bill/people) * ((100+ tip)/100)
print(f"The amount you need to pay is {b}")
